# Generated by Django 2.2.3 on 2019-07-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sampleBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_image', models.ImageField(height_field=270, upload_to='aaaa', width_field=288.52)),
                ('description', models.TextField(null=True)),
                ('telegram_link', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
