# Generated by Django 2.2.3 on 2019-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplebot',
            name='sample_image',
            field=models.ImageField(height_field=270, upload_to='images/%y-%m-%d_%H:%M', width_field=288.52),
        ),
    ]
