# Generated by Django 2.2.3 on 2019-07-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0005_auto_20190718_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplebot',
            name='sample_image',
            field=models.ImageField(height_field=270, upload_to='attach-images/%y-%m-%d_%H:%M', width_field=288.52),
        ),
    ]
