# Generated by Django 2.2.3 on 2019-07-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0008_auto_20190718_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplebot',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
