# Generated by Django 2.2.3 on 2019-07-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0012_sampledetailbot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sampleDetailBot',
        ),
    ]
