# Generated by Django 2.2.3 on 2019-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0013_delete_sampledetailbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherSampleBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('sample_image', models.ImageField(null=True, upload_to='sample_image_path')),
                ('description', models.TextField(null=True)),
                ('telegram_link', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
